CC := cc
CFLAGS := -O2 -Wall -Wextra -std=c11
SRC := src/tinyssg.c src/md4c.c src/md4c-html.c src/entity.c
BIN := tinyssg
INPUT := input
OUTPUT := output

.PHONY: all clean build run

all: build

build: $(BIN)

$(BIN): $(SRC)
	$(CC) $(CFLAGS) $^ -o $@

clean:
	rm -f $(BIN)

run: build
	./$(BIN)
# This is maybe slightly dumb, but idc.

AMALGAMATION := tinyssg_amalgamated.c
SRC_FILES := src/md4c.c src/md4c-html.c src/entity.c src/tinyssg.c
HDR_FILES := src/md4c.h src/md4c-html.h src/entity.h

.PHONY: amalgamate

amalgamate:
	@echo "// this is a generated single-file amalgamation of tinyssg + dependencies" > $(AMALGAMATION)
	@echo "// autogenerated - do not edit" >> $(AMALGAMATION)
	@echo >> $(AMALGAMATION)
	@for f in $(HDR_FILES); do \
		echo "// --- begin $$f ---" >> $(AMALGAMATION); \
		cat $$f >> $(AMALGAMATION); \
		echo "// --- end $$f ---" >> $(AMALGAMATION); \
		echo >> $(AMALGAMATION); \
	done
	@for f in $(SRC_FILES); do \
		echo "// --- begin $$f ---" >> $(AMALGAMATION); \
		sed '/#include.*md4c\.h/d;/#include.*md4c-html\.h/d;/#include.*entity\.h/d' $$f >> $(AMALGAMATION); \
		echo "// --- end $$f ---" >> $(AMALGAMATION); \
		echo >> $(AMALGAMATION); \
	done
	@echo "[+] created single amalgamated source: $(AMALGAMATION)"

